substitutions:
  _REGION: "us-central1"
  _REPO_AR: "apps"
  _SERVICE: "hello-cr"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_AR}/${_SERVICE}:$SHORT_SHA','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_AR}/${_SERVICE}:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_AR}/${_SERVICE}:$SHORT_SHA
      - --region=${_REGION}
      - --allow-unauthenticated
      - --service-account=cicd-deployer@$PROJECT_ID.iam.gserviceaccount.com

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_AR}/${_SERVICE}:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
